package app.repository.enums;

public enum UserDAO {
    USERNAME_NOT_FOUND,
    USERNAME_ALREADY_EXISTS,
    PHONE_NUMBER_ALREADY_EXISTS,
    USER_SAVED_SUCCESSFULLY,
    UNEXPECTED_ERROR,
    USER_EDIT_SUCCESSFULLY,
    USER_DELETE_SUCCESSFULLY,
}
