server.port=8080
spring.datasource.url=jdbc:sqlite:database/secondhand.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
token.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
token.expiration=86400000
